check if best spot price location supports resource group
the location suggested by the spot calculation sometimes do not
support the creation of Resource Groups  which is a requirement
for `mapt`, In those cases we just use a default region

we get the following error when a region is not usable:

```
Diagnostics:
  azure-native:resources:ResourceGroup (az-ghrunner-awd-rg):
    error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" [...]
```